{"stackTrace": [["/var/task/main.py", 23, "handler", "s3_client.download_file(bucket, key, download_path)"], ["/var/task/boto3/s3/inject.py", 172, "download_file", "extra_args=ExtraArgs, callback=Callback)"], ["/var/task/boto3/s3/transfer.py", 307, "download_file", "future.result()"], ["/var/task/s3transfer/futures.py", 73, "result", "return self._coordinator.result()"], ["/var/task/s3transfer/futures.py", 233, "result", "raise self._exception"]], "errorType": "ClientError", "errorMessage": "An error occurred (403) when calling the HeadObject operation: Forbidden"}